apiVersion: v1
items:
- apiVersion: v1
  data:
    default.conf: |
      server {
        listen 80 proxy_protocol;

        location / {
          proxy_pass http://debugger.k8s-debugger.svc.cluster.local;
        }
      }
  kind: ConfigMap
  metadata:
    name: nginx-config
    namespace: k8s-debugger
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
