apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger
  namespace: k8s-debugger
  labels:
    app: k8s-debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-debugger
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-debugger
    spec:
      volumes:
        - name: test-pv-storage
          persistentVolumeClaim:
            claimName: test-pv-performance-claim
        - name: nginx-config
          configMap:
            defaultMode: 420
            name: nginx-config
      containers:
        - image: guilhermeoki/debugger:v0.1.2
          name: debugger
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
          ports:
            - containerPort: 80
              name: debugger-port
            - containerPort: 443
              name: auxiliar-port
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/tmp/"
              name: test-pv-storage
      restartPolicy: Always
